#!/bin/sh
#
# This script takes an appropriately formatted ISO and lets you burn a CD-R
# in such a way that is acceptable to the Sega Dreamcast.
#
# Adapted from David Brownlee's cd-burn-netbsd script:
#   https://github.com/abs0/dc-burn-netbsd
#

set -ex

iso_image="$1"

if [ -z "${iso_image}" ]; then
  echo "fatal: expected an ISO image" 1>&2
  exit 1
fi


prepare_audio_track() {
  audio_file=$1
  echo -n "${audio_file}: "
  if [ ! -f ${audio_file} ] ; then
      dd if=/dev/zero bs=2352 count=300 of=$audio_file # Min 4 seconds audio
  else
      echo "already present"
  fi
}

run_cdrecord() {
  echo cdrecord "$@"
}

echo; echo ">> Create audio track"
prepare_audio_track audio.raw

echo; echo ">> Burn CD"
opt_cdrecord="driveropts=burnfree gracetime=3"
run_cdrecord $opt_cdrecord -multi -audio audio.raw
run_cdrecord $opt_cdrecord -multi -multi -xa -eject "${iso_image}"
